# user www-data;

worker_processes auto;

events {
    worker_connections 1024;
}

# env DOMAIN_NAME;
env WP_FPM_HOST;
env PHP_FPM_PORT;

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 64;

    server_tokens off;

    server {
        listen 80;
        server_name localhost;

        root /var/www/html/wordpress;
        index index.php index.html; 
        
        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        location ~ \.php$ {
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            # include snippets/fastcgi-php.conf;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}